---
apiVersion: v1
kind: Service
metadata:
  name: webappreact
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 3000
  selector:
    app: webappreact
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webappreact
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webappreact
  template:
    metadata:
      labels:
        app: webappreact
    spec:
      containers:
        - name: webappreact
          image: webappreact
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "200m"
              memory: "300Mi"
          env:
            - name: PORT
              value: "3000"
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: webappreact-external
##  annotations:
##    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
#spec:
#  type: LoadBalancer
#  selector:
#    app: webappreact
#  ports:
#    - name: http
#      port: 80
#      targetPort: 3000
